database:
  url: sqlite:///platipuslogs.db
logs:
  root_path: logs/
modes:
  development:
    console: true
    file: true
    level: DEBUG
  production:
    console: false
    file: true
    level: WARN
  testing:
    console: true
    file: false
    level: INFO
